### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by stuartshields** [humanmade/platform_chassis_extension#13]
So a recent update requires for all Chassis extensions to use `_` instead of `-`. We need to rename this to:
- `platform_chassis_extension`

See https://github.com/Chassis for how the new naming conventions are done.

**Comment by rmccue** [comment]
Done. Will need to update altis-local-chassis too.

**Comment by rmccue** [comment]
Filed https://github.com/humanmade/altis-local-chassis/pull/34 for follow-up.
