### ISSUE TITLE
Consider including Chassis/Mailhog

### ISSUE THREAD

**Issue by johnbillion** [humanmade/platform_chassis_extension#3]
Mailhog is very handy for logging outgoing emails during development, particularly because email sent from unauthenticated servers will rarely actually arrive at their destination, and particularly for avoiding unintentionally sending emails to actual users.

The Chassis/Mailhog extension installs Mailhog and configures sendmail on the server to send all emails through it.

I think this is a good candidate for installing by default.

**Comment by roborourke** [comment]
I'm good with this
